# Generated by Django 4.2.2 on 2023-06-13 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastrando', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
